module-template: ! 'module MODULE_NAME where

'
extensions:
  TemplateHaskell: true
  OverloadedStrings: true
  TypeFamilies: true
  MultiParamTypeClasses: true
environment: default
cabal-file: project.cabal
version: 1
ghc-args: []
excluded-modules: []
